name: 🧪 E2E Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up latest LTS JDK (Java 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Run Maven tests
      - name: Run Tests with Maven
        run: mvn clean test

      # 4️⃣ Upload test reports (surefire)
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      # 5️⃣ (Optional) Upload Extent/Allure HTML reports if you use them
      - name: Upload HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: |
            target/extent-report/
            target/allure-report/
          if-no-files-found: ignore
